### ISSUE TITLE
Documentation consistency

### ISSUE THREAD

**Issue by petyaracz** [ethersphere/swarm-guide#119]
## Label use

- have a setup of *thing name (acronym) (link to discussion)* for first mentions and acronyms for subsequent mentions in s9
- maybe everywhere?

## Comb together warnings / notes

- bring together separate warning boxes if they refer to the same thing

## Parallelise discussion where needed

- e.g. s2 installation

**Comment by petyaracz** [comment]
can someone assign this to *me*? thx

**Comment by justelad** [comment]
@petyaracz is this still relevant?
