### ISSUE TITLE
make html fails, because could not import extension sphinx_tabs.tabs

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm-guide#132]
I activated a virtualenv (Python 2.7.15rc1, pip 19.0.2). Then installed sphinx as per the documentation. Running `make html` prints this error message:
> Running Sphinx v1.8.4
> Extension error:
> Could not import extension sphinx_tabs.tabs (exception: No module named sphinx_tabs.tabs)

**Comment by skylenet** [comment]
See https://github.com/ethersphere/swarm-guide/pull/133 

You need to install `sphinx-tabs`

`pip install sphinx-tabs`
