### ISSUE TITLE
Wrong instructions in manual connect (--nodiscover)

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm-guide#136]
`--nodiscover` flag is not implemented anymore. This section needs to be updated to instruct how to manually control connection. It should also be made clearer that it doesn't give full control of connectivity, only of the boostrapping.

https://swarm-guide.readthedocs.io/en/latest/gettingstarted.html#adding-enodes-manually

**Comment by nonsense** [comment]
`--nodiscover` section is removed now.
