### ISSUE TITLE
Incorrect usage for swarm cli

### ISSUE THREAD

**Issue by readytopark** [ethersphere/swarm-guide#17]
http://swarm-guide.readthedocs.io/en/latest/usage.html

`swarm up --bzzapi http://swarm-gateways.net /path/to/file/or/directory`

returns error with swarm 1.5.6-unstable.

```
Incorrect Usage.

up [arguments...]

"upload a file or directory to swarm using the HTTP API and prints the root hash",

flag provided but not defined: -bzzapi
```

it worked with the command below by putting `up` before the path

`swarm --bzzapi http://swarm-gateways.net up /path/to/file/or/directory`

either the document or the cli should be fixed.

**Comment by zelig** [comment]
thanks @readytopark , fixed
