### ISSUE TITLE
Default use case should be at the top

### ISSUE THREAD

**Issue by homotopycolimit** [ethersphere/swarm-guide#20]
At the top of the how-to-use-swarm section should be the default swarm connected to testnet paired with geth on ropsten.
Only later should we introduce the options of running your own network, singleton mode and the rest.
Many (most?) users start at the top of the documentation and work their way down. 
I have already answered many questions from people somewhat lost with a --verbosity(6) --maxpeers(0) setup coming from the docs.

**Comment by zelig** [comment]
fixed in https://github.com/ethersphere/swarm-guide/commit/0487875709c72e30568721c5dcd78448a09f664e
