### ISSUE TITLE
$DATADIR not compatible with --testnet

### ISSUE THREAD

**Issue by homotopycolimit** [ethersphere/swarm-guide#21]
There is an inconsistency in the docs as to which data directory to use and where the keystore is.

If we start geth with --datadir=X --testnet then the actual datadir will be X/testnet.
Swarm on the other hand doe s not add a /testnet subdirectory so we will have to specify its datadir as X/datadir. Thus there is confusion because $DATADIR is not the datadir.

I suggest we do away with the variable $DATADIR entirely and just spell it out at /path/to/data/. It makes it easier to understand (but harder to copy-paste).

Also there is a difference between geth account new and geth --testnet account new!

**Comment by justelad** [comment]
@homotopycolimit is this still relevant or can i close this?

**Comment by homotopycolimit** [comment]
close it.
