### ISSUE TITLE
Installing from source part not complete

### ISSUE THREAD

**Issue by nagydani** [ethersphere/swarm-guide#38]
If a naïve user follows the instructions of this section, she would encounter dependency problems while installing ```geth```. This would be helped by replacing ```go install``` with ```go get```.
However, it might be better just to reference the corresponding part of ```geth``` documentation rather than repeating it here.

**Comment by homotopycolimit** [comment]
why do we use `go install` at all and not just `make geth`. The latter is far easier to use.
