### ISSUE TITLE
Simplify introduction

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm-guide#66]
The introduction and "basics" section in the documentation is too long and too complicated. We should cater for the reader who is wondering about how to migrate from web2 to web3, who should be able to read an overview in 5 minutes and understand most of what is written. With the current text, I don't think that's at all the case.

Ideally the swarm page would whet the apetite with slogan claims, the introduction/basics should elaborate briefly on key topics that are clearly labelled and recognizable from the homepage. Anything more elaborate should be in the architecture section.

**Comment by justelad** [comment]
@nolash you can make github close issues directly when merging PRs:
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by nolash** [comment]
@justelad but the intro isn't simplified, so the issue is not solved

**Comment by justelad** [comment]
hm. ok. then i don't understand why the dangling PR was opened and referenced this issue in the first place.

**Comment by justelad** [comment]
and in general - i think that the introduction section can be cut down to maybe 3 paragraphs, add a couple of videos that we have from the resources so that users could actually get an `introduction`. then the rest can actually go into the resources section (about... team, roadmap, etc)

**Comment by nolash** [comment]
We have a policy of pre-emptive PRs no?

**Comment by nolash** [comment]
Maybe it doesn't fit well here. So ok, no PR unless it fixes the issue.

**Comment by justelad** [comment]
or PR even if it doesn't fix the issue but if it doesn't advance anywhere - deem for closure. If there's a problem - we can keep track of it with an issue, rather with an issue and a stale PR

**Comment by nolash** [comment]
Don't understand :)

**Comment by justelad** [comment]
@zelig your opinion about the introduction section?

**Comment by zelig** [comment]
just write one, and PR it :) @justelad
