### ISSUE TITLE
gettingstarted: Wrong information for private swarm

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm-guide#68]
In the section "running a private swarm" it's written that:

> First you fire up a number of swarm instances, following the instructions above. You can keep the same datadir, since all node-specific info will reside under $DATADIR/bzz-$BZZKEY/ Just make sure that you create an account for each instance of swarm you want to run.

However, if you try to do this, you get the error:

`Fatal: Error starting protocol stack: datadir already used by another process`

Setting the `--ipcpath` explicitly to a different ipc file does not help.

I presume the documentation's expectations here are wrong?

**Comment by homotopycolimit** [comment]
> I presume the documentation's expectations here are wrong?

documentation should be correct. Is it maybe a bug?

Or are you trying to use not just the same datadir but also the same bzzaccount?

**Comment by justelad** [comment]
@nolash @homotopycolimit is this still relevant? can i close?

**Comment by nolash** [comment]
I removed the section in the doc.
