### ISSUE TITLE
swarm-guide POC3 review: installation and ens chapters

### ISSUE THREAD

**Issue by justelad** [ethersphere/swarm-guide#74]
@nonsense please review the following [documentation](https://swarm-guide.readthedocs.io/en/docs-overhaul) chapters:
- installation and updates
- ENS chapter

Below is a list of criteria to give better guidelines on what we should look for when reviewing the documentation in order to focus efforts in the right direction.

--
  
Language criteria:
- Plain words: Extent to which the vocabulary is easily understood
- Readability: Ease with which the reader can follow the argument of the text

Design criteria:
- Graphic elements: Use of tables, bullet lists, graphs, charts, diagrams - if a diagram is missing - please open an issue describing what needs to be done

Structure criteria:
- Quality of the chapter's organisation in relation to its function
- Impression: Attractiveness and approachability of the document’s overall appearance

Relationship criteria:
- Audience: Appropriateness to the knowledge and skills of the users

Content criteria:
- Relevance: How relevant the content is to the recipient 
- Correctness: Are the commands that are in use up-to-date?
- Action: Clarity about what action is required of the user

Please submit all PRs to `swarm-guide/docs-overhaul` branch.
If there are any blockers - please address them within the scope of this issue.

**Comment by nonsense** [comment]
Hi @justelad ,

Sorry for being behind with helping on the Documentation front.

I think the two chapters are pretty well explained.

Here is an improvement PR: https://github.com/ethersphere/swarm-guide/pull/87

**Comment by justelad** [comment]
@nonsense,
thanks for the elaborate review 👍 🍺 

regarding design - noted - will do one pass over everything once all of the PRs are merged.
regarding correctness - i think we could already change the references from `swarm-network-rewrite` to `ethereum/go-ethereum`, what do you think?

**Comment by nonsense** [comment]
@justelad I don't have an opinion on that one.

**Comment by justelad** [comment]
ok. i'll correct it as part of my PR.

**Comment by justelad** [comment]
https://github.com/ethersphere/swarm-guide/pull/88/commits/d41acb241a14cf87047c86cc7c9a32b32462217e
