### ISSUE TITLE
swarm-guide POC3 review: up/downloading and getting started

### ISSUE THREAD

**Issue by justelad** [ethersphere/swarm-guide#75]
@nolash please review the following [documentation](https://swarm-guide.readthedocs.io/en/docs-overhaul) chapters:
- uploading and downloading
- getting started

Below is a list of criteria to give better guidelines on what we should look for when reviewing the documentation in order to focus efforts in the right direction.

--
  
Language criteria:
- Plain words: Extent to which the vocabulary is easily understood
- Readability: Ease with which the reader can follow the argument of the text

Design criteria:
- Graphic elements: Use of tables, bullet lists, graphs, charts, diagrams - if a diagram is missing - please open an issue describing what needs to be done

Structure criteria:
- Quality of the chapter's organisation in relation to its function
- Impression: Attractiveness and approachability of the document’s overall appearance

Relationship criteria:
- Audience: Appropriateness to the knowledge and skills of the users

Content criteria:
- Relevance: How relevant the content is to the recipient 
- Correctness: Are the commands that are in use up-to-date?
- Action: Clarity about what action is required of the user

Please submit all PRs to `swarm-guide/docs-overhaul` branch.
If there are any blockers - please address them within the scope of this issue.

**Comment by justelad** [comment]
@nolash can we close this?

**Comment by nolash** [comment]
Apart from this being linked to the introduction-issue, I think everything else in getting started is addressed.
