### ISSUE TITLE
swarm-guide POC3 review: FUSE & manifests

### ISSUE THREAD

**Issue by justelad** [ethersphere/swarm-guide#77]
@holisticode please review the following [documentation](https://swarm-guide.readthedocs.io/en/docs-overhaul) chapters:
- FUSE
- Manifests

Below is a list of criteria to give better guidelines on what we should look for when reviewing the documentation in order to focus efforts in the right direction.

--
  
Language criteria:
- Plain words: Extent to which the vocabulary is easily understood
- Readability: Ease with which the reader can follow the argument of the text

Design criteria:
- Graphic elements: Use of tables, bullet lists, graphs, charts, diagrams - if a diagram is missing - please open an issue describing what needs to be done

Structure criteria:
- Quality of the chapter's organisation in relation to its function
- Impression: Attractiveness and approachability of the document’s overall appearance

Relationship criteria:
- Audience: Appropriateness to the knowledge and skills of the users

Content criteria:
- Relevance: How relevant the content is to the recipient 
- Correctness: Are the commands that are in use up-to-date?
- Action: Clarity about what action is required of the user

Please submit all PRs to `swarm-guide/docs-overhaul` branch.
If there are any blockers - please address them within the scope of this issue.

**Comment by homotopycolimit** [comment]
```
To mount a Swarm manifest, first upload a content to Swarm using the swarm up command.
You can also upload an empty folder using swarm –recursive up.
Once you get the returned manifest hash, use it to mount the manifest to a mount point
```

perhaps in future we should upload an empty directory and give it an ENS name so that people can mount `swarm fs mount emptyswarmdir.eth /path/to/mountpoint`

**Comment by homotopycolimit** [comment]
I wonder if we need to include `--ipcpath <path-to-bzzd.ipc>` with each of the example commands. I assume this is only needed when not using the default location. yes?
