### ISSUE TITLE
swarm-guide POC3 review: PSS & MRU

### ISSUE THREAD

**Issue by justelad** [ethersphere/swarm-guide#79]
@janos please review the following [documentation](https://swarm-guide.readthedocs.io/en/docs-overhaul) chapters:
- PSS
- Mutable Resource Updates

Below is a list of criteria to give better guidelines on what we should look for when reviewing the documentation in order to focus efforts in the right direction.

--
  
Language criteria:
- Plain words: Extent to which the vocabulary is easily understood
- Readability: Ease with which the reader can follow the argument of the text

Design criteria:
- Graphic elements: Use of tables, bullet lists, graphs, charts, diagrams - if a diagram is missing - please open an issue describing what needs to be done

Structure criteria:
- Quality of the chapter's organisation in relation to its function
- Impression: Attractiveness and approachability of the document’s overall appearance

Relationship criteria:
- Audience: Appropriateness to the knowledge and skills of the users

Content criteria:
- Relevance: How relevant the content is to the recipient 
- Correctness: Are the commands that are in use up-to-date?
- Action: Clarity about what action is required of the user

Please submit all PRs to `swarm-guide/docs-overhaul` branch.
If there are any blockers - please address them within the scope of this issue.

**Comment by janos** [comment]
MRU documentation is very clear and easy to follow and understand. There is only one small change addressed by the PR.

PSS documentation has good explanations of how it works but it lacks the examples how to configure and send messages. This documentation may not need that details, but needs to mention the ways how pss can be used. It is not clear what actions are required by the user.

**Comment by justelad** [comment]
@janos what about the examples for the pss section? can you do it or do we need to call in @nolash ?

**Comment by janos** [comment]
@justelad I am not familiar with PSS from the user perspective, I believe that @nolash would provide much better examples.

**Comment by justelad** [comment]
@nolash you're hereby called to the flag

**Comment by justelad** [comment]
closing this with the future prospects of having proper `web3` bindings for `pss` that would make this area of the documentation easier to maintain and explain.
