### ISSUE TITLE
revisit roadmap and update it accordingly

### ISSUE THREAD

**Issue by justelad** [ethersphere/swarm-guide#89]
our roadmap that we link to from the new documentation is out of date.
the last status updates are from 2017 and we should update it with relevant information for users to take seriously.

optionally we should link to our ethersphere project roadmap kanban board and make it publicly accessible with read-only permissions so that users could explore and see our progress in real-time.

**Comment by homotopycolimit** [comment]
https://github.com/orgs/ethersphere/projects/5 is publicly available already.

**Comment by justelad** [comment]
awesome 👍

**Comment by justelad** [comment]
thoroughly explain in https://github.com/ethersphere/go-ethereum/issues/805
